version: '3.8'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: eshopMaster
    ports:
      - "13306:3306"

  redis:
    image: redis:latest
    ports:
      - "16379:6379"

  kafka:
    image: 'bitnami/kafka:3.6.0'
    ports:
      - '19092:9092'
      - '19094:9094'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CREATE_TOPICS=eshop:3:1
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true # #
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092,CONTROLLER://:9093,EXTERNAL://0.0.0.0:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER

  etcd:
    image: 'bitnami/etcd:3.5.9'
    ports:
      - '12379:2379'
      - '12380:2380'
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    container_name: es_eshop
    environment:
      - discovery.type=single-node
      - "xpack.security.enabled=false"
    ports:
      - "19200:9200"
