// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"eshop/bff/ioc"
	"eshop/bff/web"
)

// Injectors from wire.go:

func InitApp() *App {
	orderHandler := web.NewOrderHandler()
	hertz := ioc.InitGinServer(orderHandler)
	app := &App{
		WebServer: hertz,
	}
	return app
}
